# Lab 3: Identifying ML Problems, Selecting Open Datasets, and Drawing a Methodology Diagram
### ARTI 308 – Machine Learning

### Group Members

| Names | ID |
| --- | --- |
| Arwa Alkhathlan | 2250030009 |
| Noor Albuainain | 2250030050 |
| Zainab Alharbi | 2250030246 |
| Joud Albeijan | 2250030261 |
| Sheehana Alghamdi | 2250030084 |
| Reem Alshehab | 2250030257 |

### Part 1: Choosing an Open Dataset

**Dataset:** Global Video Game Sales
##### link: https://www.kaggle.com/datasets/samanfatima7/cleaned-global-video-game-sales-dataset

### Part 2: Defining the Machine Learning Problem

* Is this a regression, classification, or clustering problem?

Regression

* Is there a target variable?

Global_Sales — a continuous numeric value representing total worldwide sales in millions of units.

* What is the model expected to learn or predict?

The model is going to learn the relationship between a video game's descriptive attributes its platform, release year, genre, and publisher and how well it sells worldwide. Once trained, it should be able to prediact a new game expected Global_Sales in millions of units.

* Write a short problem description in your own words.

this project is to create a regression model based on the dataset Global Video Game Sales to predict the total number of sales of a video game globally. Every row in the dataset is a video game with it's details as shown in the table below

| Column | Description |
| --- | --- |
| **Rank** | Integer ranking of the game based on sales |
| **Name** | Name of the video game |
| **Platform** | Gaming platform (e.g., PS4, Xbox, Wii) |
| **Year** | Year of release |
| **Genre** | Category of the game (e.g., Action, Sports) |
| **Publisher** | Company that published the game |
| **NA_Sales** | Sales in North America (millions) |
| **EU_Sales** | Sales in Europe (millions) |
| **JP_Sales** | Sales in Japan (millions) |
| **Other_Sales** | Sales in other regions (millions) |
| **Global_Sales** | Total worldwide sales (millions) |

We need to make a regression model using all these features (Platform, Year, Genre, Publisher) to predict the 'Global_Sales' variable for a given record. with this model we can estimate the success of a game prior to its release based on past performances. since the the target column(Global_Sales) is continuous quantity and not a categorical one, it is a regression problem.

## Part 3: Loading and Inspecting the Dataset in Python

In [1]:
import pandas as pd

In [2]:
# Load the dataset
df = pd.read_csv("cleaned_global_video_game_sales.csv")

In [3]:
# Display it's shape 
print("Shape:", df.shape)

Shape: (11470, 11)

In [4]:
# Preview the first few rows
df.head()

,Rank,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
0,1,Wii Sports,Wii,2006,Sports,Nintendo,41.49,29.02,3.77,8.46,82.74
1,2,Super Mario Bros,NES,1985,Platform,Nintendo,29.08,3.58,6.81,0.77,40.24
2,3,Mario Kart Wii,Wii,2008,Racing,Nintendo,15.85,12.88,3.79,3.31,35.82
3,4,Wii Sports Resort,Wii,2009,Sports,Nintendo,15.75,11.01,3.28,2.96,33.00
4,5,Pokemon RedPokemon Blue,GB,1996,Role Playing,Nintendo,11.27,8.89,10.22,1.00,31.37

In [5]:
# Check column names and data types
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11470 entries, 0 to 11469
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Rank          11470 non-null  int64
 1   Name          11470 non-null  object
 2   Platform      11470 non-null  object
 3   Year          11470 non-null  int64
 4   Genre         11470 non-null  object
 5   Publisher     11470 non-null  object
 6   NA_Sales      11470 non-null  float64
 7   EU_Sales      11470 non-null  float64
 8   JP_Sales      11470 non-null  float64
 9   Other_Sales   11470 non-null  float64
 10  Global_Sales  11470 non-null  float64
dtypes: float64(5), int64(2), object(4)
memory usage: 985.8+ KB

In [8]:
# statistics for numeric columns
df.describe()

,Rank,Year,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
count,11470.000000,11470.000000,11470.000000,11470.000000,11470.000000,11470.000000,11470.000000
mean,8293.056757,1976.790846,0.285488,0.157714,0.104155,0.050868,0.598443
std,4917.895465,238.905301,0.940182,0.572520,0.364020,0.214558,1.789962
min,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.010000
25%,3963.250000,2002.000000,0.000000,0.000000,0.000000,0.000000,0.060000
50%,8325.500000,2007.000000,0.070000,0.020000,0.000000,0.010000,0.170000
75%,12644.750000,2010.000000,0.240000,0.110000,0.060000,0.030000,0.500000
max,16599.000000,2020.000000,41.490000,29.020000,10.220000,10.570000,82.740000

### Part 4: Designing the Methodology Diagram